on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Aliyun Container Registry
        uses: aliyun/acr-login@v1
        with:
          region-id: cn-hangzhou
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          endpoint: registry.cn-hangzhou.aliyuncs.com

      - name: Build and push
        run: |
          docker-compose -f docs/dev-ops/docker-compose-aliyun.yml build
          docker-compose -f docs/dev-ops/docker-compose-aliyun.yml push